// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type FeatureInitParameters struct {

	// Specifies the name of the feature to register.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Should this feature be Registered or Unregistered?
	Registered *bool `json:"registered,omitempty" tf:"registered,omitempty"`
}

type FeatureObservation struct {

	// Specifies the name of the feature to register.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Should this feature be Registered or Unregistered?
	Registered *bool `json:"registered,omitempty" tf:"registered,omitempty"`
}

type FeatureParameters struct {

	// Specifies the name of the feature to register.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Should this feature be Registered or Unregistered?
	// +kubebuilder:validation:Optional
	Registered *bool `json:"registered" tf:"registered,omitempty"`
}

type ResourceProviderRegistrationInitParameters struct {

	// A list of feature blocks as defined below.
	Feature []FeatureInitParameters `json:"feature,omitempty" tf:"feature,omitempty"`

	// The namespace of the Resource Provider which should be registered. Changing this forces a new resource to be created.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ResourceProviderRegistrationObservation struct {

	// A list of feature blocks as defined below.
	Feature []FeatureObservation `json:"feature,omitempty" tf:"feature,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The namespace of the Resource Provider which should be registered. Changing this forces a new resource to be created.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ResourceProviderRegistrationParameters struct {

	// A list of feature blocks as defined below.
	// +kubebuilder:validation:Optional
	Feature []FeatureParameters `json:"feature,omitempty" tf:"feature,omitempty"`

	// The namespace of the Resource Provider which should be registered. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// ResourceProviderRegistrationSpec defines the desired state of ResourceProviderRegistration
type ResourceProviderRegistrationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ResourceProviderRegistrationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ResourceProviderRegistrationInitParameters `json:"initProvider,omitempty"`
}

// ResourceProviderRegistrationStatus defines the observed state of ResourceProviderRegistration.
type ResourceProviderRegistrationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ResourceProviderRegistrationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ResourceProviderRegistration is the Schema for the ResourceProviderRegistrations API. Manages the Registration of a Resource Provider.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azure}
type ResourceProviderRegistration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ResourceProviderRegistrationSpec   `json:"spec"`
	Status ResourceProviderRegistrationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ResourceProviderRegistrationList contains a list of ResourceProviderRegistrations
type ResourceProviderRegistrationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ResourceProviderRegistration `json:"items"`
}

// Repository type metadata.
var (
	ResourceProviderRegistration_Kind             = "ResourceProviderRegistration"
	ResourceProviderRegistration_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ResourceProviderRegistration_Kind}.String()
	ResourceProviderRegistration_KindAPIVersion   = ResourceProviderRegistration_Kind + "." + CRDGroupVersion.String()
	ResourceProviderRegistration_GroupVersionKind = CRDGroupVersion.WithKind(ResourceProviderRegistration_Kind)
)

func init() {
	SchemeBuilder.Register(&ResourceProviderRegistration{}, &ResourceProviderRegistrationList{})
}
