/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type FunctionJavascriptUdaInitParameters struct {

	// One or more input blocks as defined below.
	Input []InputInitParameters `json:"input,omitempty" tf:"input,omitempty"`

	// An output block as defined below.
	Output []OutputInitParameters `json:"output,omitempty" tf:"output,omitempty"`

	// The JavaScript of this UDA Function.
	Script *string `json:"script,omitempty" tf:"script,omitempty"`
}

type FunctionJavascriptUdaObservation struct {

	// The ID of the Stream Analytics JavaScript UDA Function.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// One or more input blocks as defined below.
	Input []InputObservation `json:"input,omitempty" tf:"input,omitempty"`

	// An output block as defined below.
	Output []OutputObservation `json:"output,omitempty" tf:"output,omitempty"`

	// The JavaScript of this UDA Function.
	Script *string `json:"script,omitempty" tf:"script,omitempty"`

	// The resource ID of the Stream Analytics Job where this Function should be created. Changing this forces a new resource to be created.
	StreamAnalyticsJobID *string `json:"streamAnalyticsJobId,omitempty" tf:"stream_analytics_job_id,omitempty"`
}

type FunctionJavascriptUdaParameters struct {

	// One or more input blocks as defined below.
	Input []InputParameters `json:"input,omitempty" tf:"input,omitempty"`

	// An output block as defined below.
	Output []OutputParameters `json:"output,omitempty" tf:"output,omitempty"`

	// The JavaScript of this UDA Function.
	Script *string `json:"script,omitempty" tf:"script,omitempty"`

	// The resource ID of the Stream Analytics Job where this Function should be created. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=Job
	// +crossplane:generate:reference:extractor=github.com/upbound/provider-azure/apis/rconfig.ExtractResourceID()
	// +kubebuilder:validation:Optional
	StreamAnalyticsJobID *string `json:"streamAnalyticsJobId,omitempty" tf:"stream_analytics_job_id,omitempty"`

	// Reference to a Job to populate streamAnalyticsJobId.
	// +kubebuilder:validation:Optional
	StreamAnalyticsJobIDRef *v1.Reference `json:"streamAnalyticsJobIdRef,omitempty" tf:"-"`

	// Selector for a Job to populate streamAnalyticsJobId.
	// +kubebuilder:validation:Optional
	StreamAnalyticsJobIDSelector *v1.Selector `json:"streamAnalyticsJobIdSelector,omitempty" tf:"-"`
}

type InputInitParameters struct {

	// Is this input parameter a configuration parameter? Defaults to false.
	ConfigurationParameter *bool `json:"configurationParameter,omitempty" tf:"configuration_parameter,omitempty"`

	// The input data type of this JavaScript Function. Possible values include any, array, bigint, datetime, float, nvarchar(max) and record.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type InputObservation struct {

	// Is this input parameter a configuration parameter? Defaults to false.
	ConfigurationParameter *bool `json:"configurationParameter,omitempty" tf:"configuration_parameter,omitempty"`

	// The input data type of this JavaScript Function. Possible values include any, array, bigint, datetime, float, nvarchar(max) and record.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type InputParameters struct {

	// Is this input parameter a configuration parameter? Defaults to false.
	ConfigurationParameter *bool `json:"configurationParameter,omitempty" tf:"configuration_parameter,omitempty"`

	// The input data type of this JavaScript Function. Possible values include any, array, bigint, datetime, float, nvarchar(max) and record.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type OutputInitParameters struct {

	// The output data type from this JavaScript Function. Possible values include any, array, bigint, datetime, float, nvarchar(max) and record.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type OutputObservation struct {

	// The output data type from this JavaScript Function. Possible values include any, array, bigint, datetime, float, nvarchar(max) and record.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type OutputParameters struct {

	// The output data type from this JavaScript Function. Possible values include any, array, bigint, datetime, float, nvarchar(max) and record.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// FunctionJavascriptUdaSpec defines the desired state of FunctionJavascriptUda
type FunctionJavascriptUdaSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FunctionJavascriptUdaParameters `json:"forProvider"`
	// THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored
	// unless the relevant Crossplane feature flag is enabled, and may be
	// changed or removed without notice.
	InitProvider FunctionJavascriptUdaInitParameters `json:"initProvider,omitempty"`
}

// FunctionJavascriptUdaStatus defines the observed state of FunctionJavascriptUda.
type FunctionJavascriptUdaStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FunctionJavascriptUdaObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// FunctionJavascriptUda is the Schema for the FunctionJavascriptUdas API. Manages a JavaScript UDA Function within a Stream Analytics Streaming Job.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azure},path=functionjavascriptudas
type FunctionJavascriptUda struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.input) || has(self.initProvider.input)",message="input is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.output) || has(self.initProvider.output)",message="output is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.script) || has(self.initProvider.script)",message="script is a required parameter"
	Spec   FunctionJavascriptUdaSpec   `json:"spec"`
	Status FunctionJavascriptUdaStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FunctionJavascriptUdaList contains a list of FunctionJavascriptUdas
type FunctionJavascriptUdaList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FunctionJavascriptUda `json:"items"`
}

// Repository type metadata.
var (
	FunctionJavascriptUda_Kind             = "FunctionJavascriptUda"
	FunctionJavascriptUda_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FunctionJavascriptUda_Kind}.String()
	FunctionJavascriptUda_KindAPIVersion   = FunctionJavascriptUda_Kind + "." + CRDGroupVersion.String()
	FunctionJavascriptUda_GroupVersionKind = CRDGroupVersion.WithKind(FunctionJavascriptUda_Kind)
)

func init() {
	SchemeBuilder.Register(&FunctionJavascriptUda{}, &FunctionJavascriptUdaList{})
}
