// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1beta1

// Hub marks this type as a conversion hub.
func (tr *HPCCache) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HPCCacheAccessPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HPCCacheBlobNFSTarget) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HPCCacheBlobTarget) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HPCCacheNFSTarget) Hub() {}
