# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: machinelearningservices.azure.m.upbound.io/v1beta1
kind: DatastoreFileshare
metadata:
  annotations:
    meta.upbound.io/example-id: machinelearningservices/v1beta1/datastorefileshare
  labels:
    testing.upbound.io/example-name: example
  name: exampledatastore
  namespace: upbound-system
spec:
  forProvider:
    accountKeySecretRef:
      key: attribute.primary_access_key
      name: example-mlds-fileshare-storage-account
    description: Example file share datastore
    storageFileshareIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    workspaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: storage.azure.m.upbound.io/v1beta1
kind: Share
metadata:
  annotations:
    meta.upbound.io/example-id: machinelearningservices/v1beta1/datastorefileshare
  labels:
    testing.upbound.io/example-name: example
  name: mldsfileshare
  namespace: upbound-system
spec:
  forProvider:
    quota: 1
    storageAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: machinelearningservices.azure.m.upbound.io/v1beta1
kind: Workspace
metadata:
  annotations:
    meta.upbound.io/example-id: machinelearningservices/v1beta1/datastorefileshare
  labels:
    testing.upbound.io/example-name: example
  name: datastorefileshare
  namespace: upbound-system
spec:
  forProvider:
    applicationInsightsIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    identity:
      type: SystemAssigned
    keyVaultIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    storageAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: insights.azure.m.upbound.io/v1beta1
kind: ApplicationInsights
metadata:
  annotations:
    meta.upbound.io/example-id: machinelearningservices/v1beta1/datastorefileshare
  labels:
    testing.upbound.io/example-name: example
  name: datastorefileshare
  namespace: upbound-system
spec:
  forProvider:
    applicationType: web
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: keyvault.azure.m.upbound.io/v1beta1
kind: Vault
metadata:
  annotations:
    meta.upbound.io/example-id: machinelearningservices/v1beta1/datastorefileshare
  labels:
    testing.upbound.io/example-name: example
  name: uptest-${Rand.RFC1123Subdomain}
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: standard
    tenantId: ${data.azurerm_client_config.current.tenant_id}

---

apiVersion: storage.azure.m.upbound.io/v1beta1
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: machinelearningservices/v1beta1/datastorefileshare
  labels:
    testing.upbound.io/example-name: example
  name: mldsfshare6f3a
  namespace: upbound-system
spec:
  forProvider:
    accountReplicationType: LRS
    accountTier: Standard
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
  writeConnectionSecretToRef:
    name: example-mlds-fileshare-storage-account

---

apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: machinelearningservices/v1beta1/datastorefileshare
  labels:
    testing.upbound.io/example-name: example
  name: datastorefileshare
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
