# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: oracle.azure.upbound.io/v1beta1
kind: AutonomousDatabaseBackup
metadata:
  annotations:
    meta.upbound.io/example-id: oracle/v1beta1/autonomousdatabasebackup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    autonomousDatabaseIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    backup_type: Full
    retentionPeriodInDays: 120

---

apiVersion: oracle.azure.upbound.io/v1beta1
kind: AutonomousDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: oracle/v1beta1/autonomousdatabasebackup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: East US
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: oracle/v1beta1/autonomousdatabasebackup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: East US
