# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: sql.azure.m.upbound.io/v1beta1
kind: MSSQLDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1beta2/mssqldatabase
  labels:
    testing.upbound.io/example-name: examplemssqldatabase
  name: examplemssqldatabase
  namespace: upbound-system
spec:
  forProvider:
    collation: SQL_Latin1_General_CP1_CI_AS
    elasticPoolIdSelector:
      matchLabels:
        testing.upbound.io/example-name: mssqldatabasepool
    serverIdSelector:
      matchLabels:
        testing.upbound.io/example-name: mssqldatabasesrv
    skuName: ElasticPool
    tags:
      foo: bar
---
apiVersion: sql.azure.m.upbound.io/v1beta1
kind: MSSQLElasticPool
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1beta2/mssqldatabase
  labels:
    testing.upbound.io/example-name: mssqldatabasepool
  name: mssqldatabasepool
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
    maxSizeGb: 5
    perDatabaseSettings:
      maxCapacity: 4
      minCapacity: 1
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: mssqldatabase-rg
    serverNameSelector:
      matchLabels:
        testing.upbound.io/example-name: mssqldatabasesrv
    sku:
      capacity: 4
      family: Gen5
      name: GP_Gen5
      tier: GeneralPurpose
---
apiVersion: sql.azure.m.upbound.io/v1beta1
kind: MSSQLServer
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1beta2/mssqldatabase
    uptest.upbound.io/timeout: "3600"
  labels:
    testing.upbound.io/example-name: mssqldatabasesrv
  name: sqldatabasev1beta1ns
  namespace: upbound-system
spec:
  forProvider:
    administratorLogin: 4dm1n157r470r
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: mssqldatabase-rg
    version: "12.0"
---
apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1beta2/mssqldatabase
  labels:
    testing.upbound.io/example-name: mssqldatabase-rg
  name: sqldatabasev1beta1ns
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
---
apiVersion: sql.azure.m.upbound.io/v1beta1
kind: MSSQLDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1beta2/mssqldatabase
  labels:
    testing.upbound.io/example-name: examplemssqldatabasecopy
  name: examplemssqldatabasecopy
  namespace: upbound-system
spec:
  forProvider:
    collation: SQL_Latin1_General_CP1_CI_AS
    createMode: Copy
    creationSourceDatabaseIdSelector:
      matchLabels:
        testing.upbound.io/example-name: examplemssqldatabase
    elasticPoolIdSelector:
      matchLabels:
        testing.upbound.io/example-name: mssqldatabasepool
    serverIdSelector:
      matchLabels:
        testing.upbound.io/example-name: mssqldatabasesrv
    tags:
      foo: bar
---
apiVersion: v1
data:
  example-key: dGVzdFBhc3N3b3JkITEyMw==
kind: Secret
metadata:
  name: example-secret
  namespace: upbound-system
type: Opaque
