// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AdministratorAccountInitParameters struct {

	// Specifies a list of group email addresses. Changing this forces a new resource to be created.
	Groups []*string `json:"groups,omitempty" tf:"groups,omitempty"`

	// Specifies a list of user email addresses. Changing this forces a new resource to be created.
	Users []*string `json:"users,omitempty" tf:"users,omitempty"`
}

type AdministratorAccountObservation struct {

	// Specifies a list of group email addresses. Changing this forces a new resource to be created.
	Groups []*string `json:"groups,omitempty" tf:"groups,omitempty"`

	// Specifies a list of user email addresses. Changing this forces a new resource to be created.
	Users []*string `json:"users,omitempty" tf:"users,omitempty"`
}

type AdministratorAccountParameters struct {

	// Specifies a list of group email addresses. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Groups []*string `json:"groups,omitempty" tf:"groups,omitempty"`

	// Specifies a list of user email addresses. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Users []*string `json:"users,omitempty" tf:"users,omitempty"`
}

type AutomaticResourcePredictionInitParameters struct {

	// Specifies the desired balance between cost and performance. Possible values are MostCostEffective, MoreCostEffective, Balanced, MorePerformance, and BestPerformance. Defaults to Balanced.
	PredictionPreference *string `json:"predictionPreference,omitempty" tf:"prediction_preference,omitempty"`
}

type AutomaticResourcePredictionObservation struct {

	// Specifies the desired balance between cost and performance. Possible values are MostCostEffective, MoreCostEffective, Balanced, MorePerformance, and BestPerformance. Defaults to Balanced.
	PredictionPreference *string `json:"predictionPreference,omitempty" tf:"prediction_preference,omitempty"`
}

type AutomaticResourcePredictionParameters struct {

	// Specifies the desired balance between cost and performance. Possible values are MostCostEffective, MoreCostEffective, Balanced, MorePerformance, and BestPerformance. Defaults to Balanced.
	// +kubebuilder:validation:Optional
	PredictionPreference *string `json:"predictionPreference,omitempty" tf:"prediction_preference,omitempty"`
}

type AzureDevopsOrganizationInitParameters struct {

	// One or more organization blocks as defined below.
	Organization []OrganizationInitParameters `json:"organization,omitempty" tf:"organization,omitempty"`

	// A permission block as defined below. Changing this forces a new resource to be created.
	Permission *PermissionInitParameters `json:"permission,omitempty" tf:"permission,omitempty"`
}

type AzureDevopsOrganizationObservation struct {

	// One or more organization blocks as defined below.
	Organization []OrganizationObservation `json:"organization,omitempty" tf:"organization,omitempty"`

	// A permission block as defined below. Changing this forces a new resource to be created.
	Permission *PermissionObservation `json:"permission,omitempty" tf:"permission,omitempty"`
}

type AzureDevopsOrganizationParameters struct {

	// One or more organization blocks as defined below.
	// +kubebuilder:validation:Optional
	Organization []OrganizationParameters `json:"organization" tf:"organization,omitempty"`

	// A permission block as defined below. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Permission *PermissionParameters `json:"permission,omitempty" tf:"permission,omitempty"`
}

type FridayScheduleInitParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type FridayScheduleObservation struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type FridayScheduleParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	// +kubebuilder:validation:Optional
	Count *float64 `json:"count" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	// +kubebuilder:validation:Optional
	Time *string `json:"time" tf:"time,omitempty"`
}

type IdentityInitParameters struct {

	// Specifies a list of User Assigned Managed Identity IDs.
	// +listType=set
	IdentityIds []*string `json:"identityIds,omitempty" tf:"identity_ids,omitempty"`

	// The type of managed service identity. The only possible value is UserAssigned.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type IdentityObservation struct {

	// Specifies a list of User Assigned Managed Identity IDs.
	// +listType=set
	IdentityIds []*string `json:"identityIds,omitempty" tf:"identity_ids,omitempty"`

	// The type of managed service identity. The only possible value is UserAssigned.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type IdentityParameters struct {

	// Specifies a list of User Assigned Managed Identity IDs.
	// +kubebuilder:validation:Optional
	// +listType=set
	IdentityIds []*string `json:"identityIds" tf:"identity_ids,omitempty"`

	// The type of managed service identity. The only possible value is UserAssigned.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type ImageInitParameters struct {

	// List of aliases to reference the image by.
	Aliases []*string `json:"aliases,omitempty" tf:"aliases,omitempty"`

	// The percentage of the buffer to be allocated to this image. Possible values are * or between 0 and 100. Defaults to *.
	Buffer *string `json:"buffer,omitempty" tf:"buffer,omitempty"`

	// The resource id of the image.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The image to use from a well-known set of images made available to customers.
	WellKnownImageName *string `json:"wellKnownImageName,omitempty" tf:"well_known_image_name,omitempty"`
}

type ImageObservation struct {

	// List of aliases to reference the image by.
	Aliases []*string `json:"aliases,omitempty" tf:"aliases,omitempty"`

	// The percentage of the buffer to be allocated to this image. Possible values are * or between 0 and 100. Defaults to *.
	Buffer *string `json:"buffer,omitempty" tf:"buffer,omitempty"`

	// The resource id of the image.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The image to use from a well-known set of images made available to customers.
	WellKnownImageName *string `json:"wellKnownImageName,omitempty" tf:"well_known_image_name,omitempty"`
}

type ImageParameters struct {

	// List of aliases to reference the image by.
	// +kubebuilder:validation:Optional
	Aliases []*string `json:"aliases,omitempty" tf:"aliases,omitempty"`

	// The percentage of the buffer to be allocated to this image. Possible values are * or between 0 and 100. Defaults to *.
	// +kubebuilder:validation:Optional
	Buffer *string `json:"buffer,omitempty" tf:"buffer,omitempty"`

	// The resource id of the image.
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The image to use from a well-known set of images made available to customers.
	// +kubebuilder:validation:Optional
	WellKnownImageName *string `json:"wellKnownImageName,omitempty" tf:"well_known_image_name,omitempty"`
}

type KeyVaultManagementInitParameters struct {

	// Specifies where to store certificates on the machine.
	CertificateStoreLocation *string `json:"certificateStoreLocation,omitempty" tf:"certificate_store_location,omitempty"`

	// Name of the certificate store to use on the machine. Possible values are My and Root.
	CertificateStoreName *string `json:"certificateStoreName,omitempty" tf:"certificate_store_name,omitempty"`

	// Defines if the key of the certificates should be exportable. Defaults to false.
	KeyExportEnabled *bool `json:"keyExportEnabled,omitempty" tf:"key_export_enabled,omitempty"`

	// A list of versionless_id from Azure Key vault certificates to install on all machines in the pool.
	KeyVaultCertificateIds []*string `json:"keyVaultCertificateIds,omitempty" tf:"key_vault_certificate_ids,omitempty"`
}

type KeyVaultManagementObservation struct {

	// Specifies where to store certificates on the machine.
	CertificateStoreLocation *string `json:"certificateStoreLocation,omitempty" tf:"certificate_store_location,omitempty"`

	// Name of the certificate store to use on the machine. Possible values are My and Root.
	CertificateStoreName *string `json:"certificateStoreName,omitempty" tf:"certificate_store_name,omitempty"`

	// Defines if the key of the certificates should be exportable. Defaults to false.
	KeyExportEnabled *bool `json:"keyExportEnabled,omitempty" tf:"key_export_enabled,omitempty"`

	// A list of versionless_id from Azure Key vault certificates to install on all machines in the pool.
	KeyVaultCertificateIds []*string `json:"keyVaultCertificateIds,omitempty" tf:"key_vault_certificate_ids,omitempty"`
}

type KeyVaultManagementParameters struct {

	// Specifies where to store certificates on the machine.
	// +kubebuilder:validation:Optional
	CertificateStoreLocation *string `json:"certificateStoreLocation,omitempty" tf:"certificate_store_location,omitempty"`

	// Name of the certificate store to use on the machine. Possible values are My and Root.
	// +kubebuilder:validation:Optional
	CertificateStoreName *string `json:"certificateStoreName,omitempty" tf:"certificate_store_name,omitempty"`

	// Defines if the key of the certificates should be exportable. Defaults to false.
	// +kubebuilder:validation:Optional
	KeyExportEnabled *bool `json:"keyExportEnabled,omitempty" tf:"key_export_enabled,omitempty"`

	// A list of versionless_id from Azure Key vault certificates to install on all machines in the pool.
	// +kubebuilder:validation:Optional
	KeyVaultCertificateIds []*string `json:"keyVaultCertificateIds" tf:"key_vault_certificate_ids,omitempty"`
}

type ManagedDevopsPoolInitParameters struct {

	// An azure_devops_organization block as defined below.
	AzureDevopsOrganization *AzureDevopsOrganizationInitParameters `json:"azureDevopsOrganization,omitempty" tf:"azure_devops_organization,omitempty"`

	// The ID of the Dev Center project.
	// +crossplane:generate:reference:type=github.com/upbound/provider-azure/v2/apis/cluster/devcenter/v1beta1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	DevCenterProjectID *string `json:"devCenterProjectId,omitempty" tf:"dev_center_project_id,omitempty"`

	// Reference to a Project in devcenter to populate devCenterProjectId.
	// +kubebuilder:validation:Optional
	DevCenterProjectIDRef *v1.Reference `json:"devCenterProjectIdRef,omitempty" tf:"-"`

	// Selector for a Project in devcenter to populate devCenterProjectId.
	// +kubebuilder:validation:Optional
	DevCenterProjectIDSelector *v1.Selector `json:"devCenterProjectIdSelector,omitempty" tf:"-"`

	// An identity block as defined below.
	Identity *IdentityInitParameters `json:"identity,omitempty" tf:"identity,omitempty"`

	// The Azure Region where the Managed DevOps Pool should exist. Changing this forces a new resource to be created.
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// Defines how many resources can there be created at any given time. Possible values range between 1 and 10000.
	MaximumConcurrency *float64 `json:"maximumConcurrency,omitempty" tf:"maximum_concurrency,omitempty"`

	// A stateful_agent block as defined below.
	StatefulAgent *StatefulAgentInitParameters `json:"statefulAgent,omitempty" tf:"stateful_agent,omitempty"`

	// A stateless_agent block as defined below.
	StatelessAgent *StatelessAgentInitParameters `json:"statelessAgent,omitempty" tf:"stateless_agent,omitempty"`

	// A mapping of tags which should be assigned to the Managed DevOps Pool.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// A virtual_machine_scale_set_fabric block as defined below.
	VirtualMachineScaleSetFabric *VirtualMachineScaleSetFabricInitParameters `json:"virtualMachineScaleSetFabric,omitempty" tf:"virtual_machine_scale_set_fabric,omitempty"`

	// Specifies the work folder for every agent in the pool.
	WorkFolder *string `json:"workFolder,omitempty" tf:"work_folder,omitempty"`
}

type ManagedDevopsPoolObservation struct {

	// An azure_devops_organization block as defined below.
	AzureDevopsOrganization *AzureDevopsOrganizationObservation `json:"azureDevopsOrganization,omitempty" tf:"azure_devops_organization,omitempty"`

	// The ID of the Dev Center project.
	DevCenterProjectID *string `json:"devCenterProjectId,omitempty" tf:"dev_center_project_id,omitempty"`

	// The ID of the Managed DevOps Pool.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// An identity block as defined below.
	Identity *IdentityObservation `json:"identity,omitempty" tf:"identity,omitempty"`

	// The Azure Region where the Managed DevOps Pool should exist. Changing this forces a new resource to be created.
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// Defines how many resources can there be created at any given time. Possible values range between 1 and 10000.
	MaximumConcurrency *float64 `json:"maximumConcurrency,omitempty" tf:"maximum_concurrency,omitempty"`

	// The name of the Resource Group where the Managed DevOps Pool should exist. Changing this forces a new resource to be created.
	ResourceGroupName *string `json:"resourceGroupName,omitempty" tf:"resource_group_name,omitempty"`

	// A stateful_agent block as defined below.
	StatefulAgent *StatefulAgentObservation `json:"statefulAgent,omitempty" tf:"stateful_agent,omitempty"`

	// A stateless_agent block as defined below.
	StatelessAgent *StatelessAgentObservation `json:"statelessAgent,omitempty" tf:"stateless_agent,omitempty"`

	// A mapping of tags which should be assigned to the Managed DevOps Pool.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// A virtual_machine_scale_set_fabric block as defined below.
	VirtualMachineScaleSetFabric *VirtualMachineScaleSetFabricObservation `json:"virtualMachineScaleSetFabric,omitempty" tf:"virtual_machine_scale_set_fabric,omitempty"`

	// Specifies the work folder for every agent in the pool.
	WorkFolder *string `json:"workFolder,omitempty" tf:"work_folder,omitempty"`
}

type ManagedDevopsPoolParameters struct {

	// An azure_devops_organization block as defined below.
	// +kubebuilder:validation:Optional
	AzureDevopsOrganization *AzureDevopsOrganizationParameters `json:"azureDevopsOrganization,omitempty" tf:"azure_devops_organization,omitempty"`

	// The ID of the Dev Center project.
	// +crossplane:generate:reference:type=github.com/upbound/provider-azure/v2/apis/cluster/devcenter/v1beta1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	DevCenterProjectID *string `json:"devCenterProjectId,omitempty" tf:"dev_center_project_id,omitempty"`

	// Reference to a Project in devcenter to populate devCenterProjectId.
	// +kubebuilder:validation:Optional
	DevCenterProjectIDRef *v1.Reference `json:"devCenterProjectIdRef,omitempty" tf:"-"`

	// Selector for a Project in devcenter to populate devCenterProjectId.
	// +kubebuilder:validation:Optional
	DevCenterProjectIDSelector *v1.Selector `json:"devCenterProjectIdSelector,omitempty" tf:"-"`

	// An identity block as defined below.
	// +kubebuilder:validation:Optional
	Identity *IdentityParameters `json:"identity,omitempty" tf:"identity,omitempty"`

	// The Azure Region where the Managed DevOps Pool should exist. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// Defines how many resources can there be created at any given time. Possible values range between 1 and 10000.
	// +kubebuilder:validation:Optional
	MaximumConcurrency *float64 `json:"maximumConcurrency,omitempty" tf:"maximum_concurrency,omitempty"`

	// The name of the Resource Group where the Managed DevOps Pool should exist. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/upbound/provider-azure/v2/apis/cluster/azure/v1beta1.ResourceGroup
	// +kubebuilder:validation:Optional
	ResourceGroupName *string `json:"resourceGroupName,omitempty" tf:"resource_group_name,omitempty"`

	// Reference to a ResourceGroup in azure to populate resourceGroupName.
	// +kubebuilder:validation:Optional
	ResourceGroupNameRef *v1.Reference `json:"resourceGroupNameRef,omitempty" tf:"-"`

	// Selector for a ResourceGroup in azure to populate resourceGroupName.
	// +kubebuilder:validation:Optional
	ResourceGroupNameSelector *v1.Selector `json:"resourceGroupNameSelector,omitempty" tf:"-"`

	// A stateful_agent block as defined below.
	// +kubebuilder:validation:Optional
	StatefulAgent *StatefulAgentParameters `json:"statefulAgent,omitempty" tf:"stateful_agent,omitempty"`

	// A stateless_agent block as defined below.
	// +kubebuilder:validation:Optional
	StatelessAgent *StatelessAgentParameters `json:"statelessAgent,omitempty" tf:"stateless_agent,omitempty"`

	// A mapping of tags which should be assigned to the Managed DevOps Pool.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// A virtual_machine_scale_set_fabric block as defined below.
	// +kubebuilder:validation:Optional
	VirtualMachineScaleSetFabric *VirtualMachineScaleSetFabricParameters `json:"virtualMachineScaleSetFabric,omitempty" tf:"virtual_machine_scale_set_fabric,omitempty"`

	// Specifies the work folder for every agent in the pool.
	// +kubebuilder:validation:Optional
	WorkFolder *string `json:"workFolder,omitempty" tf:"work_folder,omitempty"`
}

type ManualResourcePredictionFridayScheduleInitParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type ManualResourcePredictionFridayScheduleObservation struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type ManualResourcePredictionFridayScheduleParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	// +kubebuilder:validation:Optional
	Count *float64 `json:"count" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	// +kubebuilder:validation:Optional
	Time *string `json:"time" tf:"time,omitempty"`
}

type ManualResourcePredictionInitParameters struct {

	// A number of agents available 24/7 all week. Possible values range between 1 and maximum_concurrency.
	AllWeekSchedule *float64 `json:"allWeekSchedule,omitempty" tf:"all_week_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	FridaySchedule []FridayScheduleInitParameters `json:"fridaySchedule,omitempty" tf:"friday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	MondaySchedule []MondayScheduleInitParameters `json:"mondaySchedule,omitempty" tf:"monday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	SaturdaySchedule []SaturdayScheduleInitParameters `json:"saturdaySchedule,omitempty" tf:"saturday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	SundaySchedule []SundayScheduleInitParameters `json:"sundaySchedule,omitempty" tf:"sunday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	ThursdaySchedule []ThursdayScheduleInitParameters `json:"thursdaySchedule,omitempty" tf:"thursday_schedule,omitempty"`

	// Specifies the time zone for the predictions data to be provisioned at. Defaults to UTC.
	TimeZoneName *string `json:"timeZoneName,omitempty" tf:"time_zone_name,omitempty"`

	// One or more daily_schedule blocks as defined below.
	TuesdaySchedule []TuesdayScheduleInitParameters `json:"tuesdaySchedule,omitempty" tf:"tuesday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	WednesdaySchedule []WednesdayScheduleInitParameters `json:"wednesdaySchedule,omitempty" tf:"wednesday_schedule,omitempty"`
}

type ManualResourcePredictionMondayScheduleInitParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type ManualResourcePredictionMondayScheduleObservation struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type ManualResourcePredictionMondayScheduleParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	// +kubebuilder:validation:Optional
	Count *float64 `json:"count" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	// +kubebuilder:validation:Optional
	Time *string `json:"time" tf:"time,omitempty"`
}

type ManualResourcePredictionObservation struct {

	// A number of agents available 24/7 all week. Possible values range between 1 and maximum_concurrency.
	AllWeekSchedule *float64 `json:"allWeekSchedule,omitempty" tf:"all_week_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	FridaySchedule []FridayScheduleObservation `json:"fridaySchedule,omitempty" tf:"friday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	MondaySchedule []MondayScheduleObservation `json:"mondaySchedule,omitempty" tf:"monday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	SaturdaySchedule []SaturdayScheduleObservation `json:"saturdaySchedule,omitempty" tf:"saturday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	SundaySchedule []SundayScheduleObservation `json:"sundaySchedule,omitempty" tf:"sunday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	ThursdaySchedule []ThursdayScheduleObservation `json:"thursdaySchedule,omitempty" tf:"thursday_schedule,omitempty"`

	// Specifies the time zone for the predictions data to be provisioned at. Defaults to UTC.
	TimeZoneName *string `json:"timeZoneName,omitempty" tf:"time_zone_name,omitempty"`

	// One or more daily_schedule blocks as defined below.
	TuesdaySchedule []TuesdayScheduleObservation `json:"tuesdaySchedule,omitempty" tf:"tuesday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	WednesdaySchedule []WednesdayScheduleObservation `json:"wednesdaySchedule,omitempty" tf:"wednesday_schedule,omitempty"`
}

type ManualResourcePredictionParameters struct {

	// A number of agents available 24/7 all week. Possible values range between 1 and maximum_concurrency.
	// +kubebuilder:validation:Optional
	AllWeekSchedule *float64 `json:"allWeekSchedule,omitempty" tf:"all_week_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	// +kubebuilder:validation:Optional
	FridaySchedule []FridayScheduleParameters `json:"fridaySchedule,omitempty" tf:"friday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	// +kubebuilder:validation:Optional
	MondaySchedule []MondayScheduleParameters `json:"mondaySchedule,omitempty" tf:"monday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	// +kubebuilder:validation:Optional
	SaturdaySchedule []SaturdayScheduleParameters `json:"saturdaySchedule,omitempty" tf:"saturday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	// +kubebuilder:validation:Optional
	SundaySchedule []SundayScheduleParameters `json:"sundaySchedule,omitempty" tf:"sunday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	// +kubebuilder:validation:Optional
	ThursdaySchedule []ThursdayScheduleParameters `json:"thursdaySchedule,omitempty" tf:"thursday_schedule,omitempty"`

	// Specifies the time zone for the predictions data to be provisioned at. Defaults to UTC.
	// +kubebuilder:validation:Optional
	TimeZoneName *string `json:"timeZoneName,omitempty" tf:"time_zone_name,omitempty"`

	// One or more daily_schedule blocks as defined below.
	// +kubebuilder:validation:Optional
	TuesdaySchedule []TuesdayScheduleParameters `json:"tuesdaySchedule,omitempty" tf:"tuesday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	// +kubebuilder:validation:Optional
	WednesdaySchedule []WednesdayScheduleParameters `json:"wednesdaySchedule,omitempty" tf:"wednesday_schedule,omitempty"`
}

type ManualResourcePredictionSaturdayScheduleInitParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type ManualResourcePredictionSaturdayScheduleObservation struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type ManualResourcePredictionSaturdayScheduleParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	// +kubebuilder:validation:Optional
	Count *float64 `json:"count" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	// +kubebuilder:validation:Optional
	Time *string `json:"time" tf:"time,omitempty"`
}

type ManualResourcePredictionSundayScheduleInitParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type ManualResourcePredictionSundayScheduleObservation struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type ManualResourcePredictionSundayScheduleParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	// +kubebuilder:validation:Optional
	Count *float64 `json:"count" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	// +kubebuilder:validation:Optional
	Time *string `json:"time" tf:"time,omitempty"`
}

type ManualResourcePredictionThursdayScheduleInitParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type ManualResourcePredictionThursdayScheduleObservation struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type ManualResourcePredictionThursdayScheduleParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	// +kubebuilder:validation:Optional
	Count *float64 `json:"count" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	// +kubebuilder:validation:Optional
	Time *string `json:"time" tf:"time,omitempty"`
}

type ManualResourcePredictionTuesdayScheduleInitParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type ManualResourcePredictionTuesdayScheduleObservation struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type ManualResourcePredictionTuesdayScheduleParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	// +kubebuilder:validation:Optional
	Count *float64 `json:"count" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	// +kubebuilder:validation:Optional
	Time *string `json:"time" tf:"time,omitempty"`
}

type ManualResourcePredictionWednesdayScheduleInitParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type ManualResourcePredictionWednesdayScheduleObservation struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type ManualResourcePredictionWednesdayScheduleParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	// +kubebuilder:validation:Optional
	Count *float64 `json:"count" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	// +kubebuilder:validation:Optional
	Time *string `json:"time" tf:"time,omitempty"`
}

type MondayScheduleInitParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type MondayScheduleObservation struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type MondayScheduleParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	// +kubebuilder:validation:Optional
	Count *float64 `json:"count" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	// +kubebuilder:validation:Optional
	Time *string `json:"time" tf:"time,omitempty"`
}

type OrganizationInitParameters struct {

	// Specifies how many machines can be created at maximum in this organization out of the maximum_concurrency of the pool. Possible values range between 1 and 10000.
	Parallelism *float64 `json:"parallelism,omitempty" tf:"parallelism,omitempty"`

	// List of projects in which the pool should be created.
	Projects []*string `json:"projects,omitempty" tf:"projects,omitempty"`

	// The Azure DevOps organization URL in which the pool should be created. It must end with a letter or number.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type OrganizationObservation struct {

	// Specifies how many machines can be created at maximum in this organization out of the maximum_concurrency of the pool. Possible values range between 1 and 10000.
	Parallelism *float64 `json:"parallelism,omitempty" tf:"parallelism,omitempty"`

	// List of projects in which the pool should be created.
	Projects []*string `json:"projects,omitempty" tf:"projects,omitempty"`

	// The Azure DevOps organization URL in which the pool should be created. It must end with a letter or number.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type OrganizationParameters struct {

	// Specifies how many machines can be created at maximum in this organization out of the maximum_concurrency of the pool. Possible values range between 1 and 10000.
	// +kubebuilder:validation:Optional
	Parallelism *float64 `json:"parallelism" tf:"parallelism,omitempty"`

	// List of projects in which the pool should be created.
	// +kubebuilder:validation:Optional
	Projects []*string `json:"projects,omitempty" tf:"projects,omitempty"`

	// The Azure DevOps organization URL in which the pool should be created. It must end with a letter or number.
	// +kubebuilder:validation:Optional
	URL *string `json:"url" tf:"url,omitempty"`
}

type PermissionInitParameters struct {

	// An administrator_account block as defined below. This block is only valid when kind is set to SpecificAccounts. Changing this forces a new resource to be created.
	AdministratorAccount *AdministratorAccountInitParameters `json:"administratorAccount,omitempty" tf:"administrator_account,omitempty"`

	// Determines who has admin permissions to the Azure DevOps pool. Possible values are Inherit and SpecificAccounts. Changing this forces a new resource to be created.
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`
}

type PermissionObservation struct {

	// An administrator_account block as defined below. This block is only valid when kind is set to SpecificAccounts. Changing this forces a new resource to be created.
	AdministratorAccount *AdministratorAccountObservation `json:"administratorAccount,omitempty" tf:"administrator_account,omitempty"`

	// Determines who has admin permissions to the Azure DevOps pool. Possible values are Inherit and SpecificAccounts. Changing this forces a new resource to be created.
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`
}

type PermissionParameters struct {

	// An administrator_account block as defined below. This block is only valid when kind is set to SpecificAccounts. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	AdministratorAccount *AdministratorAccountParameters `json:"administratorAccount,omitempty" tf:"administrator_account,omitempty"`

	// Determines who has admin permissions to the Azure DevOps pool. Possible values are Inherit and SpecificAccounts. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Kind *string `json:"kind" tf:"kind,omitempty"`
}

type SaturdayScheduleInitParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type SaturdayScheduleObservation struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type SaturdayScheduleParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	// +kubebuilder:validation:Optional
	Count *float64 `json:"count" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	// +kubebuilder:validation:Optional
	Time *string `json:"time" tf:"time,omitempty"`
}

type SecurityInitParameters struct {

	// Specifies whether the agent should run in interactive mode. Defaults to false.
	InteractiveLogonEnabled *bool `json:"interactiveLogonEnabled,omitempty" tf:"interactive_logon_enabled,omitempty"`

	// A key_vault_management block as defined below.
	KeyVaultManagement *KeyVaultManagementInitParameters `json:"keyVaultManagement,omitempty" tf:"key_vault_management,omitempty"`
}

type SecurityObservation struct {

	// Specifies whether the agent should run in interactive mode. Defaults to false.
	InteractiveLogonEnabled *bool `json:"interactiveLogonEnabled,omitempty" tf:"interactive_logon_enabled,omitempty"`

	// A key_vault_management block as defined below.
	KeyVaultManagement *KeyVaultManagementObservation `json:"keyVaultManagement,omitempty" tf:"key_vault_management,omitempty"`
}

type SecurityParameters struct {

	// Specifies whether the agent should run in interactive mode. Defaults to false.
	// +kubebuilder:validation:Optional
	InteractiveLogonEnabled *bool `json:"interactiveLogonEnabled,omitempty" tf:"interactive_logon_enabled,omitempty"`

	// A key_vault_management block as defined below.
	// +kubebuilder:validation:Optional
	KeyVaultManagement *KeyVaultManagementParameters `json:"keyVaultManagement,omitempty" tf:"key_vault_management,omitempty"`
}

type StatefulAgentInitParameters struct {

	// An automatic_resource_prediction block as defined below.
	AutomaticResourcePrediction *AutomaticResourcePredictionInitParameters `json:"automaticResourcePrediction,omitempty" tf:"automatic_resource_prediction,omitempty"`

	// Configures the amount of time an agent in a stateful pool waits for new jobs before shutting down after all current and queued jobs are complete. The format for Grace Period is dd.hh:mm:ss or hh:mm:ss. Defaults to 00:00:00.
	GracePeriodTimeSpan *string `json:"gracePeriodTimeSpan,omitempty" tf:"grace_period_time_span,omitempty"`

	// A manual_resource_prediction block as defined below.
	ManualResourcePrediction *ManualResourcePredictionInitParameters `json:"manualResourcePrediction,omitempty" tf:"manual_resource_prediction,omitempty"`

	// Configures the maximum duration an agent in a stateful pool can run before it is shut down and discarded. The format for Max time to live for standby agents is dd.hh:mm:ss or hh:mm:ss. Defaults to 7.00:00:00.
	MaximumAgentLifetime *string `json:"maximumAgentLifetime,omitempty" tf:"maximum_agent_lifetime,omitempty"`
}

type StatefulAgentObservation struct {

	// An automatic_resource_prediction block as defined below.
	AutomaticResourcePrediction *AutomaticResourcePredictionObservation `json:"automaticResourcePrediction,omitempty" tf:"automatic_resource_prediction,omitempty"`

	// Configures the amount of time an agent in a stateful pool waits for new jobs before shutting down after all current and queued jobs are complete. The format for Grace Period is dd.hh:mm:ss or hh:mm:ss. Defaults to 00:00:00.
	GracePeriodTimeSpan *string `json:"gracePeriodTimeSpan,omitempty" tf:"grace_period_time_span,omitempty"`

	// A manual_resource_prediction block as defined below.
	ManualResourcePrediction *ManualResourcePredictionObservation `json:"manualResourcePrediction,omitempty" tf:"manual_resource_prediction,omitempty"`

	// Configures the maximum duration an agent in a stateful pool can run before it is shut down and discarded. The format for Max time to live for standby agents is dd.hh:mm:ss or hh:mm:ss. Defaults to 7.00:00:00.
	MaximumAgentLifetime *string `json:"maximumAgentLifetime,omitempty" tf:"maximum_agent_lifetime,omitempty"`
}

type StatefulAgentParameters struct {

	// An automatic_resource_prediction block as defined below.
	// +kubebuilder:validation:Optional
	AutomaticResourcePrediction *AutomaticResourcePredictionParameters `json:"automaticResourcePrediction,omitempty" tf:"automatic_resource_prediction,omitempty"`

	// Configures the amount of time an agent in a stateful pool waits for new jobs before shutting down after all current and queued jobs are complete. The format for Grace Period is dd.hh:mm:ss or hh:mm:ss. Defaults to 00:00:00.
	// +kubebuilder:validation:Optional
	GracePeriodTimeSpan *string `json:"gracePeriodTimeSpan,omitempty" tf:"grace_period_time_span,omitempty"`

	// A manual_resource_prediction block as defined below.
	// +kubebuilder:validation:Optional
	ManualResourcePrediction *ManualResourcePredictionParameters `json:"manualResourcePrediction,omitempty" tf:"manual_resource_prediction,omitempty"`

	// Configures the maximum duration an agent in a stateful pool can run before it is shut down and discarded. The format for Max time to live for standby agents is dd.hh:mm:ss or hh:mm:ss. Defaults to 7.00:00:00.
	// +kubebuilder:validation:Optional
	MaximumAgentLifetime *string `json:"maximumAgentLifetime,omitempty" tf:"maximum_agent_lifetime,omitempty"`
}

type StatelessAgentAutomaticResourcePredictionInitParameters struct {

	// Specifies the desired balance between cost and performance. Possible values are MostCostEffective, MoreCostEffective, Balanced, MorePerformance, and BestPerformance. Defaults to Balanced.
	PredictionPreference *string `json:"predictionPreference,omitempty" tf:"prediction_preference,omitempty"`
}

type StatelessAgentAutomaticResourcePredictionObservation struct {

	// Specifies the desired balance between cost and performance. Possible values are MostCostEffective, MoreCostEffective, Balanced, MorePerformance, and BestPerformance. Defaults to Balanced.
	PredictionPreference *string `json:"predictionPreference,omitempty" tf:"prediction_preference,omitempty"`
}

type StatelessAgentAutomaticResourcePredictionParameters struct {

	// Specifies the desired balance between cost and performance. Possible values are MostCostEffective, MoreCostEffective, Balanced, MorePerformance, and BestPerformance. Defaults to Balanced.
	// +kubebuilder:validation:Optional
	PredictionPreference *string `json:"predictionPreference,omitempty" tf:"prediction_preference,omitempty"`
}

type StatelessAgentInitParameters struct {

	// An automatic_resource_prediction block as defined below.
	AutomaticResourcePrediction *StatelessAgentAutomaticResourcePredictionInitParameters `json:"automaticResourcePrediction,omitempty" tf:"automatic_resource_prediction,omitempty"`

	// A manual_resource_prediction block as defined below.
	ManualResourcePrediction *StatelessAgentManualResourcePredictionInitParameters `json:"manualResourcePrediction,omitempty" tf:"manual_resource_prediction,omitempty"`
}

type StatelessAgentManualResourcePredictionInitParameters struct {

	// A number of agents available 24/7 all week. Possible values range between 1 and maximum_concurrency.
	AllWeekSchedule *float64 `json:"allWeekSchedule,omitempty" tf:"all_week_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	FridaySchedule []ManualResourcePredictionFridayScheduleInitParameters `json:"fridaySchedule,omitempty" tf:"friday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	MondaySchedule []ManualResourcePredictionMondayScheduleInitParameters `json:"mondaySchedule,omitempty" tf:"monday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	SaturdaySchedule []ManualResourcePredictionSaturdayScheduleInitParameters `json:"saturdaySchedule,omitempty" tf:"saturday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	SundaySchedule []ManualResourcePredictionSundayScheduleInitParameters `json:"sundaySchedule,omitempty" tf:"sunday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	ThursdaySchedule []ManualResourcePredictionThursdayScheduleInitParameters `json:"thursdaySchedule,omitempty" tf:"thursday_schedule,omitempty"`

	// Specifies the time zone for the predictions data to be provisioned at. Defaults to UTC.
	TimeZoneName *string `json:"timeZoneName,omitempty" tf:"time_zone_name,omitempty"`

	// One or more daily_schedule blocks as defined below.
	TuesdaySchedule []ManualResourcePredictionTuesdayScheduleInitParameters `json:"tuesdaySchedule,omitempty" tf:"tuesday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	WednesdaySchedule []ManualResourcePredictionWednesdayScheduleInitParameters `json:"wednesdaySchedule,omitempty" tf:"wednesday_schedule,omitempty"`
}

type StatelessAgentManualResourcePredictionObservation struct {

	// A number of agents available 24/7 all week. Possible values range between 1 and maximum_concurrency.
	AllWeekSchedule *float64 `json:"allWeekSchedule,omitempty" tf:"all_week_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	FridaySchedule []ManualResourcePredictionFridayScheduleObservation `json:"fridaySchedule,omitempty" tf:"friday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	MondaySchedule []ManualResourcePredictionMondayScheduleObservation `json:"mondaySchedule,omitempty" tf:"monday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	SaturdaySchedule []ManualResourcePredictionSaturdayScheduleObservation `json:"saturdaySchedule,omitempty" tf:"saturday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	SundaySchedule []ManualResourcePredictionSundayScheduleObservation `json:"sundaySchedule,omitempty" tf:"sunday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	ThursdaySchedule []ManualResourcePredictionThursdayScheduleObservation `json:"thursdaySchedule,omitempty" tf:"thursday_schedule,omitempty"`

	// Specifies the time zone for the predictions data to be provisioned at. Defaults to UTC.
	TimeZoneName *string `json:"timeZoneName,omitempty" tf:"time_zone_name,omitempty"`

	// One or more daily_schedule blocks as defined below.
	TuesdaySchedule []ManualResourcePredictionTuesdayScheduleObservation `json:"tuesdaySchedule,omitempty" tf:"tuesday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	WednesdaySchedule []ManualResourcePredictionWednesdayScheduleObservation `json:"wednesdaySchedule,omitempty" tf:"wednesday_schedule,omitempty"`
}

type StatelessAgentManualResourcePredictionParameters struct {

	// A number of agents available 24/7 all week. Possible values range between 1 and maximum_concurrency.
	// +kubebuilder:validation:Optional
	AllWeekSchedule *float64 `json:"allWeekSchedule,omitempty" tf:"all_week_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	// +kubebuilder:validation:Optional
	FridaySchedule []ManualResourcePredictionFridayScheduleParameters `json:"fridaySchedule,omitempty" tf:"friday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	// +kubebuilder:validation:Optional
	MondaySchedule []ManualResourcePredictionMondayScheduleParameters `json:"mondaySchedule,omitempty" tf:"monday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	// +kubebuilder:validation:Optional
	SaturdaySchedule []ManualResourcePredictionSaturdayScheduleParameters `json:"saturdaySchedule,omitempty" tf:"saturday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	// +kubebuilder:validation:Optional
	SundaySchedule []ManualResourcePredictionSundayScheduleParameters `json:"sundaySchedule,omitempty" tf:"sunday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	// +kubebuilder:validation:Optional
	ThursdaySchedule []ManualResourcePredictionThursdayScheduleParameters `json:"thursdaySchedule,omitempty" tf:"thursday_schedule,omitempty"`

	// Specifies the time zone for the predictions data to be provisioned at. Defaults to UTC.
	// +kubebuilder:validation:Optional
	TimeZoneName *string `json:"timeZoneName,omitempty" tf:"time_zone_name,omitempty"`

	// One or more daily_schedule blocks as defined below.
	// +kubebuilder:validation:Optional
	TuesdaySchedule []ManualResourcePredictionTuesdayScheduleParameters `json:"tuesdaySchedule,omitempty" tf:"tuesday_schedule,omitempty"`

	// One or more daily_schedule blocks as defined below.
	// +kubebuilder:validation:Optional
	WednesdaySchedule []ManualResourcePredictionWednesdayScheduleParameters `json:"wednesdaySchedule,omitempty" tf:"wednesday_schedule,omitempty"`
}

type StatelessAgentObservation struct {

	// An automatic_resource_prediction block as defined below.
	AutomaticResourcePrediction *StatelessAgentAutomaticResourcePredictionObservation `json:"automaticResourcePrediction,omitempty" tf:"automatic_resource_prediction,omitempty"`

	// A manual_resource_prediction block as defined below.
	ManualResourcePrediction *StatelessAgentManualResourcePredictionObservation `json:"manualResourcePrediction,omitempty" tf:"manual_resource_prediction,omitempty"`
}

type StatelessAgentParameters struct {

	// An automatic_resource_prediction block as defined below.
	// +kubebuilder:validation:Optional
	AutomaticResourcePrediction *StatelessAgentAutomaticResourcePredictionParameters `json:"automaticResourcePrediction,omitempty" tf:"automatic_resource_prediction,omitempty"`

	// A manual_resource_prediction block as defined below.
	// +kubebuilder:validation:Optional
	ManualResourcePrediction *StatelessAgentManualResourcePredictionParameters `json:"manualResourcePrediction,omitempty" tf:"manual_resource_prediction,omitempty"`
}

type StorageInitParameters struct {

	// The type of caching for the data disk. Possible values are ReadOnly and ReadWrite.
	Caching *string `json:"caching,omitempty" tf:"caching,omitempty"`

	// The initial disk size in gigabytes. Possible values range between 1 and 32767.
	DiskSizeInGb *float64 `json:"diskSizeInGb,omitempty" tf:"disk_size_in_gb,omitempty"`

	// The drive letter for the data disk.
	DriveLetter *string `json:"driveLetter,omitempty" tf:"drive_letter,omitempty"`

	// The storage account type of the data disk. Possible values are Premium_LRS, Premium_ZRS, Standard_LRS, StandardSSD_LRS, and StandardSSD_ZRS. Defaults to Standard_LRS.
	StorageAccountType *string `json:"storageAccountType,omitempty" tf:"storage_account_type,omitempty"`
}

type StorageObservation struct {

	// The type of caching for the data disk. Possible values are ReadOnly and ReadWrite.
	Caching *string `json:"caching,omitempty" tf:"caching,omitempty"`

	// The initial disk size in gigabytes. Possible values range between 1 and 32767.
	DiskSizeInGb *float64 `json:"diskSizeInGb,omitempty" tf:"disk_size_in_gb,omitempty"`

	// The drive letter for the data disk.
	DriveLetter *string `json:"driveLetter,omitempty" tf:"drive_letter,omitempty"`

	// The storage account type of the data disk. Possible values are Premium_LRS, Premium_ZRS, Standard_LRS, StandardSSD_LRS, and StandardSSD_ZRS. Defaults to Standard_LRS.
	StorageAccountType *string `json:"storageAccountType,omitempty" tf:"storage_account_type,omitempty"`
}

type StorageParameters struct {

	// The type of caching for the data disk. Possible values are ReadOnly and ReadWrite.
	// +kubebuilder:validation:Optional
	Caching *string `json:"caching,omitempty" tf:"caching,omitempty"`

	// The initial disk size in gigabytes. Possible values range between 1 and 32767.
	// +kubebuilder:validation:Optional
	DiskSizeInGb *float64 `json:"diskSizeInGb" tf:"disk_size_in_gb,omitempty"`

	// The drive letter for the data disk.
	// +kubebuilder:validation:Optional
	DriveLetter *string `json:"driveLetter,omitempty" tf:"drive_letter,omitempty"`

	// The storage account type of the data disk. Possible values are Premium_LRS, Premium_ZRS, Standard_LRS, StandardSSD_LRS, and StandardSSD_ZRS. Defaults to Standard_LRS.
	// +kubebuilder:validation:Optional
	StorageAccountType *string `json:"storageAccountType,omitempty" tf:"storage_account_type,omitempty"`
}

type SundayScheduleInitParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type SundayScheduleObservation struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type SundayScheduleParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	// +kubebuilder:validation:Optional
	Count *float64 `json:"count" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	// +kubebuilder:validation:Optional
	Time *string `json:"time" tf:"time,omitempty"`
}

type ThursdayScheduleInitParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type ThursdayScheduleObservation struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type ThursdayScheduleParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	// +kubebuilder:validation:Optional
	Count *float64 `json:"count" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	// +kubebuilder:validation:Optional
	Time *string `json:"time" tf:"time,omitempty"`
}

type TuesdayScheduleInitParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type TuesdayScheduleObservation struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type TuesdayScheduleParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	// +kubebuilder:validation:Optional
	Count *float64 `json:"count" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	// +kubebuilder:validation:Optional
	Time *string `json:"time" tf:"time,omitempty"`
}

type VirtualMachineScaleSetFabricInitParameters struct {

	// One or more image blocks as defined below.
	Image []ImageInitParameters `json:"image,omitempty" tf:"image,omitempty"`

	// The storage account type for the OS disk. Possible values are Premium, Standard, and StandardSSD. Defaults to Standard.
	OsDiskStorageAccountType *string `json:"osDiskStorageAccountType,omitempty" tf:"os_disk_storage_account_type,omitempty"`

	// A security block as defined below.
	Security *SecurityInitParameters `json:"security,omitempty" tf:"security,omitempty"`

	// The Azure SKU name of the machines in the pool.
	SkuName *string `json:"skuName,omitempty" tf:"sku_name,omitempty"`

	// A storage block as defined below.
	Storage *StorageInitParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// The subnet ID on which to put all machines created in the pool.
	// +crossplane:generate:reference:type=github.com/upbound/provider-azure/v2/apis/cluster/network/v1beta2.Subnet
	// +crossplane:generate:reference:extractor=github.com/upbound/provider-azure/v2/apis/cluster/rconfig.ExtractResourceID()
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`

	// Reference to a Subnet in network to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDRef *v1.Reference `json:"subnetIdRef,omitempty" tf:"-"`

	// Selector for a Subnet in network to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDSelector *v1.Selector `json:"subnetIdSelector,omitempty" tf:"-"`
}

type VirtualMachineScaleSetFabricObservation struct {

	// One or more image blocks as defined below.
	Image []ImageObservation `json:"image,omitempty" tf:"image,omitempty"`

	// The storage account type for the OS disk. Possible values are Premium, Standard, and StandardSSD. Defaults to Standard.
	OsDiskStorageAccountType *string `json:"osDiskStorageAccountType,omitempty" tf:"os_disk_storage_account_type,omitempty"`

	// A security block as defined below.
	Security *SecurityObservation `json:"security,omitempty" tf:"security,omitempty"`

	// The Azure SKU name of the machines in the pool.
	SkuName *string `json:"skuName,omitempty" tf:"sku_name,omitempty"`

	// A storage block as defined below.
	Storage *StorageObservation `json:"storage,omitempty" tf:"storage,omitempty"`

	// The subnet ID on which to put all machines created in the pool.
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`
}

type VirtualMachineScaleSetFabricParameters struct {

	// One or more image blocks as defined below.
	// +kubebuilder:validation:Optional
	Image []ImageParameters `json:"image" tf:"image,omitempty"`

	// The storage account type for the OS disk. Possible values are Premium, Standard, and StandardSSD. Defaults to Standard.
	// +kubebuilder:validation:Optional
	OsDiskStorageAccountType *string `json:"osDiskStorageAccountType,omitempty" tf:"os_disk_storage_account_type,omitempty"`

	// A security block as defined below.
	// +kubebuilder:validation:Optional
	Security *SecurityParameters `json:"security,omitempty" tf:"security,omitempty"`

	// The Azure SKU name of the machines in the pool.
	// +kubebuilder:validation:Optional
	SkuName *string `json:"skuName" tf:"sku_name,omitempty"`

	// A storage block as defined below.
	// +kubebuilder:validation:Optional
	Storage *StorageParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// The subnet ID on which to put all machines created in the pool.
	// +crossplane:generate:reference:type=github.com/upbound/provider-azure/v2/apis/cluster/network/v1beta2.Subnet
	// +crossplane:generate:reference:extractor=github.com/upbound/provider-azure/v2/apis/cluster/rconfig.ExtractResourceID()
	// +kubebuilder:validation:Optional
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`

	// Reference to a Subnet in network to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDRef *v1.Reference `json:"subnetIdRef,omitempty" tf:"-"`

	// Selector for a Subnet in network to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDSelector *v1.Selector `json:"subnetIdSelector,omitempty" tf:"-"`
}

type WednesdayScheduleInitParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type WednesdayScheduleObservation struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	Time *string `json:"time,omitempty" tf:"time,omitempty"`
}

type WednesdayScheduleParameters struct {

	// The number of standby agents to provision at this time. Possible values range between 0 and maximum_concurrency.
	// +kubebuilder:validation:Optional
	Count *float64 `json:"count" tf:"count,omitempty"`

	// The time of day at which the agent count changes, in 24-hour format HH:MM:SS.
	// +kubebuilder:validation:Optional
	Time *string `json:"time" tf:"time,omitempty"`
}

// ManagedDevopsPoolSpec defines the desired state of ManagedDevopsPool
type ManagedDevopsPoolSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ManagedDevopsPoolParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ManagedDevopsPoolInitParameters `json:"initProvider,omitempty"`
}

// ManagedDevopsPoolStatus defines the observed state of ManagedDevopsPool.
type ManagedDevopsPoolStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ManagedDevopsPoolObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ManagedDevopsPool is the Schema for the ManagedDevopsPools API. Manages a Managed DevOps Pool.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azure}
type ManagedDevopsPool struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.azureDevopsOrganization) || (has(self.initProvider) && has(self.initProvider.azureDevopsOrganization))",message="spec.forProvider.azureDevopsOrganization is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.maximumConcurrency) || (has(self.initProvider) && has(self.initProvider.maximumConcurrency))",message="spec.forProvider.maximumConcurrency is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.virtualMachineScaleSetFabric) || (has(self.initProvider) && has(self.initProvider.virtualMachineScaleSetFabric))",message="spec.forProvider.virtualMachineScaleSetFabric is a required parameter"
	Spec   ManagedDevopsPoolSpec   `json:"spec"`
	Status ManagedDevopsPoolStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ManagedDevopsPoolList contains a list of ManagedDevopsPools
type ManagedDevopsPoolList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ManagedDevopsPool `json:"items"`
}

// Repository type metadata.
var (
	ManagedDevopsPool_Kind             = "ManagedDevopsPool"
	ManagedDevopsPool_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ManagedDevopsPool_Kind}.String()
	ManagedDevopsPool_KindAPIVersion   = ManagedDevopsPool_Kind + "." + CRDGroupVersion.String()
	ManagedDevopsPool_GroupVersionKind = CRDGroupVersion.WithKind(ManagedDevopsPool_Kind)
)

func init() {
	SchemeBuilder.Register(&ManagedDevopsPool{}, &ManagedDevopsPoolList{})
}
