// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: CC0-1.0

package cluster

import (
	"github.com/upbound/provider-azure/v2/config/cluster/alertsmanagement"
	"github.com/upbound/provider-azure/v2/config/cluster/apimanagement"
	"github.com/upbound/provider-azure/v2/config/cluster/appplatform"
	"github.com/upbound/provider-azure/v2/config/cluster/authorization"
	"github.com/upbound/provider-azure/v2/config/cluster/automation"
	"github.com/upbound/provider-azure/v2/config/cluster/base"
	"github.com/upbound/provider-azure/v2/config/cluster/botservice"
	"github.com/upbound/provider-azure/v2/config/cluster/cache"
	"github.com/upbound/provider-azure/v2/config/cluster/cdn"
	"github.com/upbound/provider-azure/v2/config/cluster/certificateregistration"
	"github.com/upbound/provider-azure/v2/config/cluster/cognitiveservices"
	"github.com/upbound/provider-azure/v2/config/cluster/compute"
	"github.com/upbound/provider-azure/v2/config/cluster/consumption"
	"github.com/upbound/provider-azure/v2/config/cluster/containerapp"
	"github.com/upbound/provider-azure/v2/config/cluster/containerregistry"
	"github.com/upbound/provider-azure/v2/config/cluster/containerservice"
	"github.com/upbound/provider-azure/v2/config/cluster/cosmosdb"
	"github.com/upbound/provider-azure/v2/config/cluster/costmanagement"
	"github.com/upbound/provider-azure/v2/config/cluster/dashboard"
	"github.com/upbound/provider-azure/v2/config/cluster/datafactory"
	"github.com/upbound/provider-azure/v2/config/cluster/dataprotection"
	"github.com/upbound/provider-azure/v2/config/cluster/datashare"
	"github.com/upbound/provider-azure/v2/config/cluster/dbformysql"
	"github.com/upbound/provider-azure/v2/config/cluster/devices"
	"github.com/upbound/provider-azure/v2/config/cluster/eventgrid"
	"github.com/upbound/provider-azure/v2/config/cluster/eventhub"
	"github.com/upbound/provider-azure/v2/config/cluster/healthcareapis"
	"github.com/upbound/provider-azure/v2/config/cluster/insights"
	"github.com/upbound/provider-azure/v2/config/cluster/keyvault"
	"github.com/upbound/provider-azure/v2/config/cluster/kusto"
	"github.com/upbound/provider-azure/v2/config/cluster/machinelearningservices"
	"github.com/upbound/provider-azure/v2/config/cluster/management"
	"github.com/upbound/provider-azure/v2/config/cluster/netapp"
	"github.com/upbound/provider-azure/v2/config/cluster/network"
	"github.com/upbound/provider-azure/v2/config/cluster/notificationhubs"
	"github.com/upbound/provider-azure/v2/config/cluster/operationalinsights"
	"github.com/upbound/provider-azure/v2/config/cluster/orbital"
	"github.com/upbound/provider-azure/v2/config/cluster/postgresql"
	"github.com/upbound/provider-azure/v2/config/cluster/relay"
	"github.com/upbound/provider-azure/v2/config/cluster/resource"
	"github.com/upbound/provider-azure/v2/config/cluster/resources"
	"github.com/upbound/provider-azure/v2/config/cluster/security"
	"github.com/upbound/provider-azure/v2/config/cluster/securityinsights"
	"github.com/upbound/provider-azure/v2/config/cluster/servicebus"
	"github.com/upbound/provider-azure/v2/config/cluster/sql"
	"github.com/upbound/provider-azure/v2/config/cluster/storage"
	"github.com/upbound/provider-azure/v2/config/cluster/storagecache"
	"github.com/upbound/provider-azure/v2/config/cluster/storagesync"
	"github.com/upbound/provider-azure/v2/config/cluster/streamanalytics"
	"github.com/upbound/provider-azure/v2/config/cluster/web"
)

func init() {
	ProviderConfiguration.AddConfig(authorization.Configure)
	ProviderConfiguration.AddConfig(alertsmanagement.Configure)
	ProviderConfiguration.AddConfig(network.Configure)
	ProviderConfiguration.AddConfig(management.Configure)
	ProviderConfiguration.AddConfig(cache.Configure)
	ProviderConfiguration.AddConfig(resource.Configure)
	ProviderConfiguration.AddConfig(resources.Configure)
	ProviderConfiguration.AddConfig(containerapp.Configure)
	ProviderConfiguration.AddConfig(containerservice.Configure)
	ProviderConfiguration.AddConfig(postgresql.Configure)
	ProviderConfiguration.AddConfig(cosmosdb.Configure)
	ProviderConfiguration.AddConfig(sql.Configure)
	ProviderConfiguration.AddConfig(storage.Configure)
	ProviderConfiguration.AddConfig(operationalinsights.Configure)
	ProviderConfiguration.AddConfig(insights.Configure)
	ProviderConfiguration.AddConfig(devices.Configure)
	ProviderConfiguration.AddConfig(datafactory.Configure)
	ProviderConfiguration.AddConfig(apimanagement.Configure)
	ProviderConfiguration.AddConfig(healthcareapis.Configure)
	ProviderConfiguration.AddConfig(security.Configure)
	ProviderConfiguration.AddConfig(securityinsights.Configure)
	ProviderConfiguration.AddConfig(base.Configure)
	ProviderConfiguration.AddConfig(botservice.Configure)
	ProviderConfiguration.AddConfig(datashare.Configure)
	ProviderConfiguration.AddConfig(notificationhubs.Configure)
	ProviderConfiguration.AddConfig(storagesync.Configure)
	ProviderConfiguration.AddConfig(keyvault.Configure)
	ProviderConfiguration.AddConfig(eventhub.Configure)
	ProviderConfiguration.AddConfig(compute.Configure)
	ProviderConfiguration.AddConfig(containerregistry.Configure)
	ProviderConfiguration.AddConfig(dbformysql.Configure)
	ProviderConfiguration.AddConfig(netapp.Configure)
	ProviderConfiguration.AddConfig(dataprotection.Configure)
	ProviderConfiguration.AddConfig(kusto.Configure)
	ProviderConfiguration.AddConfig(storagecache.Configure)
	ProviderConfiguration.AddConfig(servicebus.Configure)
	ProviderConfiguration.AddConfig(consumption.Configure)
	ProviderConfiguration.AddConfig(streamanalytics.Configure)
	ProviderConfiguration.AddConfig(costmanagement.Configure)
	ProviderConfiguration.AddConfig(automation.Configure)
	ProviderConfiguration.AddConfig(web.Configure)
	ProviderConfiguration.AddConfig(relay.Configure)
	ProviderConfiguration.AddConfig(cdn.Configure)
	ProviderConfiguration.AddConfig(certificateregistration.Configure)
	ProviderConfiguration.AddConfig(orbital.Configure)
	ProviderConfiguration.AddConfig(appplatform.Configure)
	ProviderConfiguration.AddConfig(cognitiveservices.Configure)
	ProviderConfiguration.AddConfig(machinelearningservices.Configure)
	ProviderConfiguration.AddConfig(eventgrid.Configure)
	ProviderConfiguration.AddConfig(dashboard.Configure)
}
