// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: CC0-1.0

package config

import (
	"github.com/upbound/provider-azure/config/alertsmanagement"
	"github.com/upbound/provider-azure/config/apimanagement"
	"github.com/upbound/provider-azure/config/appplatform"
	"github.com/upbound/provider-azure/config/authorization"
	"github.com/upbound/provider-azure/config/automation"
	"github.com/upbound/provider-azure/config/base"
	"github.com/upbound/provider-azure/config/botservice"
	"github.com/upbound/provider-azure/config/cache"
	"github.com/upbound/provider-azure/config/cdn"
	"github.com/upbound/provider-azure/config/certificateregistration"
	"github.com/upbound/provider-azure/config/compute"
	"github.com/upbound/provider-azure/config/consumption"
	"github.com/upbound/provider-azure/config/containerapp"
	"github.com/upbound/provider-azure/config/containerregistry"
	"github.com/upbound/provider-azure/config/containerservice"
	"github.com/upbound/provider-azure/config/cosmosdb"
	"github.com/upbound/provider-azure/config/costmanagement"
	"github.com/upbound/provider-azure/config/datafactory"
	"github.com/upbound/provider-azure/config/dataprotection"
	"github.com/upbound/provider-azure/config/datashare"
	"github.com/upbound/provider-azure/config/dbformysql"
	"github.com/upbound/provider-azure/config/devices"
	"github.com/upbound/provider-azure/config/eventhub"
	"github.com/upbound/provider-azure/config/healthcareapis"
	"github.com/upbound/provider-azure/config/insights"
	"github.com/upbound/provider-azure/config/keyvault"
	"github.com/upbound/provider-azure/config/kusto"
	"github.com/upbound/provider-azure/config/management"
	"github.com/upbound/provider-azure/config/mariadb"
	"github.com/upbound/provider-azure/config/media"
	"github.com/upbound/provider-azure/config/netapp"
	"github.com/upbound/provider-azure/config/network"
	"github.com/upbound/provider-azure/config/notificationhubs"
	"github.com/upbound/provider-azure/config/operationalinsights"
	"github.com/upbound/provider-azure/config/orbital"
	"github.com/upbound/provider-azure/config/postgresql"
	"github.com/upbound/provider-azure/config/relay"
	"github.com/upbound/provider-azure/config/resource"
	"github.com/upbound/provider-azure/config/resources"
	"github.com/upbound/provider-azure/config/security"
	"github.com/upbound/provider-azure/config/securityinsights"
	"github.com/upbound/provider-azure/config/servicebus"
	"github.com/upbound/provider-azure/config/sql"
	"github.com/upbound/provider-azure/config/storage"
	"github.com/upbound/provider-azure/config/storagecache"
	"github.com/upbound/provider-azure/config/storagesync"
	"github.com/upbound/provider-azure/config/streamanalytics"
	"github.com/upbound/provider-azure/config/web"
)

func init() {
	ProviderConfiguration.AddConfig(authorization.Configure)
	ProviderConfiguration.AddConfig(alertsmanagement.Configure)
	ProviderConfiguration.AddConfig(network.Configure)
	ProviderConfiguration.AddConfig(management.Configure)
	ProviderConfiguration.AddConfig(media.Configure)
	ProviderConfiguration.AddConfig(cache.Configure)
	ProviderConfiguration.AddConfig(resource.Configure)
	ProviderConfiguration.AddConfig(resources.Configure)
	ProviderConfiguration.AddConfig(containerapp.Configure)
	ProviderConfiguration.AddConfig(containerservice.Configure)
	ProviderConfiguration.AddConfig(postgresql.Configure)
	ProviderConfiguration.AddConfig(cosmosdb.Configure)
	ProviderConfiguration.AddConfig(sql.Configure)
	ProviderConfiguration.AddConfig(storage.Configure)
	ProviderConfiguration.AddConfig(operationalinsights.Configure)
	ProviderConfiguration.AddConfig(insights.Configure)
	ProviderConfiguration.AddConfig(devices.Configure)
	ProviderConfiguration.AddConfig(datafactory.Configure)
	ProviderConfiguration.AddConfig(apimanagement.Configure)
	ProviderConfiguration.AddConfig(healthcareapis.Configure)
	ProviderConfiguration.AddConfig(security.Configure)
	ProviderConfiguration.AddConfig(securityinsights.Configure)
	ProviderConfiguration.AddConfig(base.Configure)
	ProviderConfiguration.AddConfig(botservice.Configure)
	ProviderConfiguration.AddConfig(datashare.Configure)
	ProviderConfiguration.AddConfig(notificationhubs.Configure)
	ProviderConfiguration.AddConfig(storagesync.Configure)
	ProviderConfiguration.AddConfig(keyvault.Configure)
	ProviderConfiguration.AddConfig(eventhub.Configure)
	ProviderConfiguration.AddConfig(mariadb.Configure)
	ProviderConfiguration.AddConfig(compute.Configure)
	ProviderConfiguration.AddConfig(containerregistry.Configure)
	ProviderConfiguration.AddConfig(dbformysql.Configure)
	ProviderConfiguration.AddConfig(netapp.Configure)
	ProviderConfiguration.AddConfig(dataprotection.Configure)
	ProviderConfiguration.AddConfig(kusto.Configure)
	ProviderConfiguration.AddConfig(storagecache.Configure)
	ProviderConfiguration.AddConfig(servicebus.Configure)
	ProviderConfiguration.AddConfig(consumption.Configure)
	ProviderConfiguration.AddConfig(streamanalytics.Configure)
	ProviderConfiguration.AddConfig(costmanagement.Configure)
	ProviderConfiguration.AddConfig(automation.Configure)
	ProviderConfiguration.AddConfig(web.Configure)
	ProviderConfiguration.AddConfig(relay.Configure)
	ProviderConfiguration.AddConfig(cdn.Configure)
	ProviderConfiguration.AddConfig(certificateregistration.Configure)
	ProviderConfiguration.AddConfig(orbital.Configure)
	ProviderConfiguration.AddConfig(appplatform.Configure)
}
