# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: cognitiveservices.azure.upbound.io/v1beta1
kind: AccountConnectionAccountManagedIdentity
metadata:
  annotations:
    meta.upbound.io/example-id: cognitiveservices/v1beta1/accountconnectionaccountmanagedidentity
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    category: AzureKeyVault
    cognitiveAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    metadata:
      ApiType: Azure
      Location: West Europe
      ResourceId: ${azurerm_key_vault.example.id}
    targetSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: cognitiveservices.azure.upbound.io/v1beta2
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: cognitiveservices/v1beta1/accountconnectionaccountmanagedidentity
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    customSubdomainName: exampleaiservices
    identity:
      type: SystemAssigned
    kind: AIServices
    location: West Europe
    projectManagementEnabled: true
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: S0

---

apiVersion: keyvault.azure.upbound.io/v1beta2
kind: Vault
metadata:
  annotations:
    meta.upbound.io/example-id: cognitiveservices/v1beta1/accountconnectionaccountmanagedidentity
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: standard
    tenantId: ${data.azurerm_client_config.current.tenant_id}

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: cognitiveservices/v1beta1/accountconnectionaccountmanagedidentity
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
