# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: cognitiveservices.azure.upbound.io/v1beta1
kind: AccountProject
metadata:
  annotations:
    meta.upbound.io/example-id: cognitiveservices/v1beta1/accountproject
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    cognitiveAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    description: Example cognitive services project
    displayName: Example Project
    identity:
      type: SystemAssigned
    location: West Europe
    tags:
      Environment: test

---

apiVersion: cognitiveservices.azure.upbound.io/v1beta2
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: cognitiveservices/v1beta1/accountproject
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    customSubdomainName: example-account-subdomain
    identity:
      type: SystemAssigned
    kind: AIServices
    location: West Europe
    projectManagementEnabled: true
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: S0

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: cognitiveservices/v1beta1/accountproject
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
