# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: containerregistry.azure.upbound.io/v1beta1
kind: CacheRule
metadata:
  annotations:
    meta.upbound.io/example-id: containerregistry/v1beta1/cacherule
  labels:
    testing.upbound.io/example-name: cache_rule
  name: cache-rule
spec:
  forProvider:
    containerRegistryIdSelector:
      matchLabels:
        testing.upbound.io/example-name: acr
    credentialSetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: acr
    sourceRepo: docker.io/hello-world
    targetRepo: target

---

apiVersion: containerregistry.azure.upbound.io/v1beta2
kind: Registry
metadata:
  annotations:
    meta.upbound.io/example-id: containerregistry/v1beta1/cacherule
  labels:
    testing.upbound.io/example-name: acr
  name: acr
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    sku: Basic

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: containerregistry/v1beta1/cacherule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
