/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type BackupPolicyDiskObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type BackupPolicyDiskParameters struct {

	// +kubebuilder:validation:Required
	BackupRepeatingTimeIntervals []*string `json:"backupRepeatingTimeIntervals" tf:"backup_repeating_time_intervals,omitempty"`

	// +kubebuilder:validation:Required
	DefaultRetentionDuration *string `json:"defaultRetentionDuration" tf:"default_retention_duration,omitempty"`

	// +kubebuilder:validation:Optional
	RetentionRule []RetentionRuleParameters `json:"retentionRule,omitempty" tf:"retention_rule,omitempty"`

	// +crossplane:generate:reference:type=BackupVault
	// +crossplane:generate:reference:extractor=github.com/upbound/official-providers/provider-azure/apis/rconfig.ExtractResourceID()
	// +kubebuilder:validation:Optional
	VaultID *string `json:"vaultId,omitempty" tf:"vault_id,omitempty"`

	// +kubebuilder:validation:Optional
	VaultIDRef *v1.Reference `json:"vaultIdRef,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	VaultIDSelector *v1.Selector `json:"vaultIdSelector,omitempty" tf:"-"`
}

type CriteriaObservation struct {
}

type CriteriaParameters struct {

	// +kubebuilder:validation:Optional
	AbsoluteCriteria *string `json:"absoluteCriteria,omitempty" tf:"absolute_criteria,omitempty"`
}

type RetentionRuleObservation struct {
}

type RetentionRuleParameters struct {

	// +kubebuilder:validation:Required
	Criteria []CriteriaParameters `json:"criteria" tf:"criteria,omitempty"`

	// +kubebuilder:validation:Required
	Duration *string `json:"duration" tf:"duration,omitempty"`

	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// +kubebuilder:validation:Required
	Priority *float64 `json:"priority" tf:"priority,omitempty"`
}

// BackupPolicyDiskSpec defines the desired state of BackupPolicyDisk
type BackupPolicyDiskSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BackupPolicyDiskParameters `json:"forProvider"`
}

// BackupPolicyDiskStatus defines the observed state of BackupPolicyDisk.
type BackupPolicyDiskStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BackupPolicyDiskObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// BackupPolicyDisk is the Schema for the BackupPolicyDisks API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azure}
type BackupPolicyDisk struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              BackupPolicyDiskSpec   `json:"spec"`
	Status            BackupPolicyDiskStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BackupPolicyDiskList contains a list of BackupPolicyDisks
type BackupPolicyDiskList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BackupPolicyDisk `json:"items"`
}

// Repository type metadata.
var (
	BackupPolicyDisk_Kind             = "BackupPolicyDisk"
	BackupPolicyDisk_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BackupPolicyDisk_Kind}.String()
	BackupPolicyDisk_KindAPIVersion   = BackupPolicyDisk_Kind + "." + CRDGroupVersion.String()
	BackupPolicyDisk_GroupVersionKind = CRDGroupVersion.WithKind(BackupPolicyDisk_Kind)
)

func init() {
	SchemeBuilder.Register(&BackupPolicyDisk{}, &BackupPolicyDiskList{})
}
