// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by angryjet. DO NOT EDIT.

package v1beta1

import xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"

// GetCondition of this SpringCloudAPIPortal.
func (mg *SpringCloudAPIPortal) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SpringCloudAPIPortal.
func (mg *SpringCloudAPIPortal) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SpringCloudAPIPortal.
func (mg *SpringCloudAPIPortal) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SpringCloudAPIPortal.
func (mg *SpringCloudAPIPortal) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SpringCloudAPIPortal.
func (mg *SpringCloudAPIPortal) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SpringCloudAPIPortal.
func (mg *SpringCloudAPIPortal) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SpringCloudAPIPortal.
func (mg *SpringCloudAPIPortal) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SpringCloudAPIPortal.
func (mg *SpringCloudAPIPortal) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SpringCloudAPIPortal.
func (mg *SpringCloudAPIPortal) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SpringCloudAPIPortal.
func (mg *SpringCloudAPIPortal) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SpringCloudAPIPortalCustomDomain.
func (mg *SpringCloudAPIPortalCustomDomain) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SpringCloudAPIPortalCustomDomain.
func (mg *SpringCloudAPIPortalCustomDomain) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SpringCloudAPIPortalCustomDomain.
func (mg *SpringCloudAPIPortalCustomDomain) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SpringCloudAPIPortalCustomDomain.
func (mg *SpringCloudAPIPortalCustomDomain) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SpringCloudAPIPortalCustomDomain.
func (mg *SpringCloudAPIPortalCustomDomain) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SpringCloudAPIPortalCustomDomain.
func (mg *SpringCloudAPIPortalCustomDomain) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SpringCloudAPIPortalCustomDomain.
func (mg *SpringCloudAPIPortalCustomDomain) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SpringCloudAPIPortalCustomDomain.
func (mg *SpringCloudAPIPortalCustomDomain) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SpringCloudAPIPortalCustomDomain.
func (mg *SpringCloudAPIPortalCustomDomain) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SpringCloudAPIPortalCustomDomain.
func (mg *SpringCloudAPIPortalCustomDomain) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SpringCloudAccelerator.
func (mg *SpringCloudAccelerator) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SpringCloudAccelerator.
func (mg *SpringCloudAccelerator) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SpringCloudAccelerator.
func (mg *SpringCloudAccelerator) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SpringCloudAccelerator.
func (mg *SpringCloudAccelerator) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SpringCloudAccelerator.
func (mg *SpringCloudAccelerator) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SpringCloudAccelerator.
func (mg *SpringCloudAccelerator) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SpringCloudAccelerator.
func (mg *SpringCloudAccelerator) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SpringCloudAccelerator.
func (mg *SpringCloudAccelerator) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SpringCloudAccelerator.
func (mg *SpringCloudAccelerator) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SpringCloudAccelerator.
func (mg *SpringCloudAccelerator) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SpringCloudActiveDeployment.
func (mg *SpringCloudActiveDeployment) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SpringCloudActiveDeployment.
func (mg *SpringCloudActiveDeployment) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SpringCloudActiveDeployment.
func (mg *SpringCloudActiveDeployment) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SpringCloudActiveDeployment.
func (mg *SpringCloudActiveDeployment) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SpringCloudActiveDeployment.
func (mg *SpringCloudActiveDeployment) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SpringCloudActiveDeployment.
func (mg *SpringCloudActiveDeployment) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SpringCloudActiveDeployment.
func (mg *SpringCloudActiveDeployment) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SpringCloudActiveDeployment.
func (mg *SpringCloudActiveDeployment) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SpringCloudActiveDeployment.
func (mg *SpringCloudActiveDeployment) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SpringCloudActiveDeployment.
func (mg *SpringCloudActiveDeployment) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SpringCloudApp.
func (mg *SpringCloudApp) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SpringCloudApp.
func (mg *SpringCloudApp) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SpringCloudApp.
func (mg *SpringCloudApp) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SpringCloudApp.
func (mg *SpringCloudApp) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SpringCloudApp.
func (mg *SpringCloudApp) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SpringCloudApp.
func (mg *SpringCloudApp) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SpringCloudApp.
func (mg *SpringCloudApp) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SpringCloudApp.
func (mg *SpringCloudApp) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SpringCloudApp.
func (mg *SpringCloudApp) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SpringCloudApp.
func (mg *SpringCloudApp) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SpringCloudAppCosmosDBAssociation.
func (mg *SpringCloudAppCosmosDBAssociation) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SpringCloudAppCosmosDBAssociation.
func (mg *SpringCloudAppCosmosDBAssociation) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SpringCloudAppCosmosDBAssociation.
func (mg *SpringCloudAppCosmosDBAssociation) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SpringCloudAppCosmosDBAssociation.
func (mg *SpringCloudAppCosmosDBAssociation) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SpringCloudAppCosmosDBAssociation.
func (mg *SpringCloudAppCosmosDBAssociation) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SpringCloudAppCosmosDBAssociation.
func (mg *SpringCloudAppCosmosDBAssociation) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SpringCloudAppCosmosDBAssociation.
func (mg *SpringCloudAppCosmosDBAssociation) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SpringCloudAppCosmosDBAssociation.
func (mg *SpringCloudAppCosmosDBAssociation) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SpringCloudAppCosmosDBAssociation.
func (mg *SpringCloudAppCosmosDBAssociation) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SpringCloudAppCosmosDBAssociation.
func (mg *SpringCloudAppCosmosDBAssociation) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SpringCloudAppMySQLAssociation.
func (mg *SpringCloudAppMySQLAssociation) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SpringCloudAppMySQLAssociation.
func (mg *SpringCloudAppMySQLAssociation) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SpringCloudAppMySQLAssociation.
func (mg *SpringCloudAppMySQLAssociation) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SpringCloudAppMySQLAssociation.
func (mg *SpringCloudAppMySQLAssociation) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SpringCloudAppMySQLAssociation.
func (mg *SpringCloudAppMySQLAssociation) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SpringCloudAppMySQLAssociation.
func (mg *SpringCloudAppMySQLAssociation) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SpringCloudAppMySQLAssociation.
func (mg *SpringCloudAppMySQLAssociation) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SpringCloudAppMySQLAssociation.
func (mg *SpringCloudAppMySQLAssociation) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SpringCloudAppMySQLAssociation.
func (mg *SpringCloudAppMySQLAssociation) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SpringCloudAppMySQLAssociation.
func (mg *SpringCloudAppMySQLAssociation) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SpringCloudAppRedisAssociation.
func (mg *SpringCloudAppRedisAssociation) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SpringCloudAppRedisAssociation.
func (mg *SpringCloudAppRedisAssociation) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SpringCloudAppRedisAssociation.
func (mg *SpringCloudAppRedisAssociation) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SpringCloudAppRedisAssociation.
func (mg *SpringCloudAppRedisAssociation) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SpringCloudAppRedisAssociation.
func (mg *SpringCloudAppRedisAssociation) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SpringCloudAppRedisAssociation.
func (mg *SpringCloudAppRedisAssociation) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SpringCloudAppRedisAssociation.
func (mg *SpringCloudAppRedisAssociation) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SpringCloudAppRedisAssociation.
func (mg *SpringCloudAppRedisAssociation) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SpringCloudAppRedisAssociation.
func (mg *SpringCloudAppRedisAssociation) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SpringCloudAppRedisAssociation.
func (mg *SpringCloudAppRedisAssociation) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SpringCloudBuildDeployment.
func (mg *SpringCloudBuildDeployment) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SpringCloudBuildDeployment.
func (mg *SpringCloudBuildDeployment) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SpringCloudBuildDeployment.
func (mg *SpringCloudBuildDeployment) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SpringCloudBuildDeployment.
func (mg *SpringCloudBuildDeployment) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SpringCloudBuildDeployment.
func (mg *SpringCloudBuildDeployment) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SpringCloudBuildDeployment.
func (mg *SpringCloudBuildDeployment) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SpringCloudBuildDeployment.
func (mg *SpringCloudBuildDeployment) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SpringCloudBuildDeployment.
func (mg *SpringCloudBuildDeployment) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SpringCloudBuildDeployment.
func (mg *SpringCloudBuildDeployment) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SpringCloudBuildDeployment.
func (mg *SpringCloudBuildDeployment) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SpringCloudBuildPackBinding.
func (mg *SpringCloudBuildPackBinding) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SpringCloudBuildPackBinding.
func (mg *SpringCloudBuildPackBinding) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SpringCloudBuildPackBinding.
func (mg *SpringCloudBuildPackBinding) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SpringCloudBuildPackBinding.
func (mg *SpringCloudBuildPackBinding) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SpringCloudBuildPackBinding.
func (mg *SpringCloudBuildPackBinding) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SpringCloudBuildPackBinding.
func (mg *SpringCloudBuildPackBinding) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SpringCloudBuildPackBinding.
func (mg *SpringCloudBuildPackBinding) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SpringCloudBuildPackBinding.
func (mg *SpringCloudBuildPackBinding) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SpringCloudBuildPackBinding.
func (mg *SpringCloudBuildPackBinding) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SpringCloudBuildPackBinding.
func (mg *SpringCloudBuildPackBinding) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SpringCloudBuilder.
func (mg *SpringCloudBuilder) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SpringCloudBuilder.
func (mg *SpringCloudBuilder) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SpringCloudBuilder.
func (mg *SpringCloudBuilder) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SpringCloudBuilder.
func (mg *SpringCloudBuilder) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SpringCloudBuilder.
func (mg *SpringCloudBuilder) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SpringCloudBuilder.
func (mg *SpringCloudBuilder) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SpringCloudBuilder.
func (mg *SpringCloudBuilder) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SpringCloudBuilder.
func (mg *SpringCloudBuilder) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SpringCloudBuilder.
func (mg *SpringCloudBuilder) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SpringCloudBuilder.
func (mg *SpringCloudBuilder) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SpringCloudCertificate.
func (mg *SpringCloudCertificate) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SpringCloudCertificate.
func (mg *SpringCloudCertificate) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SpringCloudCertificate.
func (mg *SpringCloudCertificate) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SpringCloudCertificate.
func (mg *SpringCloudCertificate) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SpringCloudCertificate.
func (mg *SpringCloudCertificate) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SpringCloudCertificate.
func (mg *SpringCloudCertificate) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SpringCloudCertificate.
func (mg *SpringCloudCertificate) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SpringCloudCertificate.
func (mg *SpringCloudCertificate) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SpringCloudCertificate.
func (mg *SpringCloudCertificate) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SpringCloudCertificate.
func (mg *SpringCloudCertificate) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SpringCloudConfigurationService.
func (mg *SpringCloudConfigurationService) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SpringCloudConfigurationService.
func (mg *SpringCloudConfigurationService) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SpringCloudConfigurationService.
func (mg *SpringCloudConfigurationService) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SpringCloudConfigurationService.
func (mg *SpringCloudConfigurationService) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SpringCloudConfigurationService.
func (mg *SpringCloudConfigurationService) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SpringCloudConfigurationService.
func (mg *SpringCloudConfigurationService) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SpringCloudConfigurationService.
func (mg *SpringCloudConfigurationService) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SpringCloudConfigurationService.
func (mg *SpringCloudConfigurationService) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SpringCloudConfigurationService.
func (mg *SpringCloudConfigurationService) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SpringCloudConfigurationService.
func (mg *SpringCloudConfigurationService) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SpringCloudContainerDeployment.
func (mg *SpringCloudContainerDeployment) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SpringCloudContainerDeployment.
func (mg *SpringCloudContainerDeployment) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SpringCloudContainerDeployment.
func (mg *SpringCloudContainerDeployment) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SpringCloudContainerDeployment.
func (mg *SpringCloudContainerDeployment) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SpringCloudContainerDeployment.
func (mg *SpringCloudContainerDeployment) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SpringCloudContainerDeployment.
func (mg *SpringCloudContainerDeployment) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SpringCloudContainerDeployment.
func (mg *SpringCloudContainerDeployment) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SpringCloudContainerDeployment.
func (mg *SpringCloudContainerDeployment) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SpringCloudContainerDeployment.
func (mg *SpringCloudContainerDeployment) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SpringCloudContainerDeployment.
func (mg *SpringCloudContainerDeployment) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SpringCloudCustomDomain.
func (mg *SpringCloudCustomDomain) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SpringCloudCustomDomain.
func (mg *SpringCloudCustomDomain) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SpringCloudCustomDomain.
func (mg *SpringCloudCustomDomain) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SpringCloudCustomDomain.
func (mg *SpringCloudCustomDomain) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SpringCloudCustomDomain.
func (mg *SpringCloudCustomDomain) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SpringCloudCustomDomain.
func (mg *SpringCloudCustomDomain) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SpringCloudCustomDomain.
func (mg *SpringCloudCustomDomain) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SpringCloudCustomDomain.
func (mg *SpringCloudCustomDomain) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SpringCloudCustomDomain.
func (mg *SpringCloudCustomDomain) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SpringCloudCustomDomain.
func (mg *SpringCloudCustomDomain) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SpringCloudCustomizedAccelerator.
func (mg *SpringCloudCustomizedAccelerator) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SpringCloudCustomizedAccelerator.
func (mg *SpringCloudCustomizedAccelerator) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SpringCloudCustomizedAccelerator.
func (mg *SpringCloudCustomizedAccelerator) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SpringCloudCustomizedAccelerator.
func (mg *SpringCloudCustomizedAccelerator) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SpringCloudCustomizedAccelerator.
func (mg *SpringCloudCustomizedAccelerator) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SpringCloudCustomizedAccelerator.
func (mg *SpringCloudCustomizedAccelerator) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SpringCloudCustomizedAccelerator.
func (mg *SpringCloudCustomizedAccelerator) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SpringCloudCustomizedAccelerator.
func (mg *SpringCloudCustomizedAccelerator) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SpringCloudCustomizedAccelerator.
func (mg *SpringCloudCustomizedAccelerator) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SpringCloudCustomizedAccelerator.
func (mg *SpringCloudCustomizedAccelerator) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SpringCloudDevToolPortal.
func (mg *SpringCloudDevToolPortal) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SpringCloudDevToolPortal.
func (mg *SpringCloudDevToolPortal) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SpringCloudDevToolPortal.
func (mg *SpringCloudDevToolPortal) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SpringCloudDevToolPortal.
func (mg *SpringCloudDevToolPortal) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SpringCloudDevToolPortal.
func (mg *SpringCloudDevToolPortal) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SpringCloudDevToolPortal.
func (mg *SpringCloudDevToolPortal) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SpringCloudDevToolPortal.
func (mg *SpringCloudDevToolPortal) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SpringCloudDevToolPortal.
func (mg *SpringCloudDevToolPortal) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SpringCloudDevToolPortal.
func (mg *SpringCloudDevToolPortal) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SpringCloudDevToolPortal.
func (mg *SpringCloudDevToolPortal) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SpringCloudGateway.
func (mg *SpringCloudGateway) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SpringCloudGateway.
func (mg *SpringCloudGateway) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SpringCloudGateway.
func (mg *SpringCloudGateway) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SpringCloudGateway.
func (mg *SpringCloudGateway) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SpringCloudGateway.
func (mg *SpringCloudGateway) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SpringCloudGateway.
func (mg *SpringCloudGateway) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SpringCloudGateway.
func (mg *SpringCloudGateway) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SpringCloudGateway.
func (mg *SpringCloudGateway) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SpringCloudGateway.
func (mg *SpringCloudGateway) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SpringCloudGateway.
func (mg *SpringCloudGateway) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SpringCloudGatewayCustomDomain.
func (mg *SpringCloudGatewayCustomDomain) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SpringCloudGatewayCustomDomain.
func (mg *SpringCloudGatewayCustomDomain) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SpringCloudGatewayCustomDomain.
func (mg *SpringCloudGatewayCustomDomain) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SpringCloudGatewayCustomDomain.
func (mg *SpringCloudGatewayCustomDomain) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SpringCloudGatewayCustomDomain.
func (mg *SpringCloudGatewayCustomDomain) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SpringCloudGatewayCustomDomain.
func (mg *SpringCloudGatewayCustomDomain) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SpringCloudGatewayCustomDomain.
func (mg *SpringCloudGatewayCustomDomain) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SpringCloudGatewayCustomDomain.
func (mg *SpringCloudGatewayCustomDomain) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SpringCloudGatewayCustomDomain.
func (mg *SpringCloudGatewayCustomDomain) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SpringCloudGatewayCustomDomain.
func (mg *SpringCloudGatewayCustomDomain) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SpringCloudJavaDeployment.
func (mg *SpringCloudJavaDeployment) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SpringCloudJavaDeployment.
func (mg *SpringCloudJavaDeployment) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SpringCloudJavaDeployment.
func (mg *SpringCloudJavaDeployment) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SpringCloudJavaDeployment.
func (mg *SpringCloudJavaDeployment) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SpringCloudJavaDeployment.
func (mg *SpringCloudJavaDeployment) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SpringCloudJavaDeployment.
func (mg *SpringCloudJavaDeployment) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SpringCloudJavaDeployment.
func (mg *SpringCloudJavaDeployment) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SpringCloudJavaDeployment.
func (mg *SpringCloudJavaDeployment) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SpringCloudJavaDeployment.
func (mg *SpringCloudJavaDeployment) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SpringCloudJavaDeployment.
func (mg *SpringCloudJavaDeployment) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SpringCloudService.
func (mg *SpringCloudService) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SpringCloudService.
func (mg *SpringCloudService) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SpringCloudService.
func (mg *SpringCloudService) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SpringCloudService.
func (mg *SpringCloudService) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SpringCloudService.
func (mg *SpringCloudService) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SpringCloudService.
func (mg *SpringCloudService) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SpringCloudService.
func (mg *SpringCloudService) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SpringCloudService.
func (mg *SpringCloudService) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SpringCloudService.
func (mg *SpringCloudService) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SpringCloudService.
func (mg *SpringCloudService) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SpringCloudStorage.
func (mg *SpringCloudStorage) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SpringCloudStorage.
func (mg *SpringCloudStorage) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SpringCloudStorage.
func (mg *SpringCloudStorage) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SpringCloudStorage.
func (mg *SpringCloudStorage) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SpringCloudStorage.
func (mg *SpringCloudStorage) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SpringCloudStorage.
func (mg *SpringCloudStorage) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SpringCloudStorage.
func (mg *SpringCloudStorage) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SpringCloudStorage.
func (mg *SpringCloudStorage) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SpringCloudStorage.
func (mg *SpringCloudStorage) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SpringCloudStorage.
func (mg *SpringCloudStorage) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}
